version: '3.6'

services:
  hug-todo:
    image: hug-todo
    build: .
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: .
        target: /app
    tty: true
    command: --reload --access-logfile "-" --error-logfile "-" --log-level debug